### ISSUE TITLE
Please add a LICENSE file of some sort

### ISSUE THREAD

**Issue by jackpal** [agordeev/BezierPathClosestPoint#1]
Thanks for making the code available and writing the informative blog post!

My daughter would like to use your code in an app she's writing for a high-school CS class project, but she is worried about licensing. Could you pick a license and add it to the project?

**Comment by agordeev** [comment]
Hi @jackpal ! The code is distributed under MIT license. I've added the LICENSE file to the repo.
Thanks for pointing on this! Good luck to your daughter with her class project.
